name: MinePaper
version: 1.0
main: org.example.Main
api-version: '1.21'

commands:
  gm:
    description: Change gamemode
    usage: /gm <c/s/a/sp> or <c/s/a/sp> + <nickname>

  heal:
    description: Heal player
    usage: /heal or <nickname>

  fly:
    description: Player fly
    usage: /fly or <nickname>

  god:
    description: God mode
    usage: /god or <nickname>

  vanish:
    description: Vanish
    usage: /vanish or <nickname>

  who:
    description: Check admin status
    usage: /who

  uuid:
    description: Show uuid
    usage: /uuid

  settime:
    description: Set times
    usage: /settime <int>

  addadmin:
    description: Add new server admin
    usage: /addadmin <nickname>

  rmadmin:
    description: Remove server admin
    usage: /rmadmin <nickname>

  tp:
    description: Teleport to player
    usage: /tp <nickname>

  tphere:
    description: Teleport player to you
    usage: /tphere <nickname>

  ttp:
    description: Teleport player to player
    usage: /ttp <player1> <player2>

  tpall:
    description: Teleport all players to you
    usage: /tpall confirm

  freeze:
    description: Freeze player or all players on server
    usage: /freeze all/player

  melt:
    description: Unfreeze player or all players on server
    usage: /melt all/player

  invsee:
    description: Show player inventory
    usage: /invsee + player

  ecsee:
    description: Show player ender chest
    usage: /ecsee + player

  clear:
    description: clear player inventory
    usage: /clear + player

  clearall:
    description: clear ender an inventory
    usage: /clearall + player







