name: MinePaper
version: 1.0
main: org.example.Main
api-version: '1.21'


permissions:
  minepaper.admin:
    description: Access to all MinePaper commands
    default: op

commands:
  gm:
    description: Change gamemode
    usage: /gm <c/s/a/sp> or <c/s/a/sp> + <nickname>

  heal:
    description: Heal player
    usage: /heal or <nickname>

  fly:
    description: Player fly
    usage: /fly or <nickname>

  god:
    description: God mode
    usage: /god or <nickname>

  vanish:
    description: Vanish
    usage: /vanish or <nickname>

  who:
    description: Check admin status
    usage: /who

  uuid:
    description: Show uuid
    usage: /uuid

  settime:
    description: Set times
    usage: /settime <int>

  addadmin:
    description: Add new server admin
    usage: /addadmin <nickname>

  rmadmin:
    description: Remove server admin
    usage: /rmadmin <nickname>

  tp:
    description: Teleport to player
    usage: /tp <nickname>

  tphere:
    description: Teleport player to you
    usage: /tphere <nickname>

  ttp:
    description: Teleport player to player
    usage: /ttp <player1> <player2>

  tpall:
    description: Teleport all players to you
    usage: /tpall confirm

  freeze:
    description: Freeze player or all players on server
    usage: /freeze all/player

  melt:
    description: Unfreeze player or all players on server
    usage: /melt all/player

  invsee:
    description: Show player inventory
    usage: /invsee + player

  ecsee:
    description: Show player ender chest
    usage: /ecsee + player

  clear:
    description: clear player inventory
    usage: /clear + player

  clearall:
    description: clear ender an inventory
    usage: /clearall + player

  kick:
    description: Kick player
    usage: /kick + player

  give:
    description: Give item(s) to player;
    usage: /give + player + item + amount;

  adminfo:
    description: Show info
    usage: /adminfo

  spectate:
    description: Spectate player
    usage: /spectate <player>

  unspectate:
    description: Stop spectating
    usage: /unspectate

  ban:
    description: Ban player
    usage: /ban <player> <reason>

  pardon:
    description: Unban player
    usage: /pardon <player>

  baninfo:
    description: Shows information about a player's ban
    usage: /baninfo <player>

  tempban:
    description: Temping ban;
    usage: /tempban <player> <time> <reason>

  mute:
    description: Mute player forever
    usage: /mute <player> <reason>

  tmute:
    description: Temp mute
    usage: /tmute <player> <time> <reason>

  unmute:
    description: Unmute player
    usage: /unmute <player>

  muteinfo:
    description: Information about target mute
    usage: /muteinfo <player>

  mutelog:
    description: Mute logs
    usage: /mutelog

  history:
    description: Player punishment history
    usage: /history <player>

  panel:
    description: open admin panel
    usage: /panel

  moditem:
    description: Give moderation item for opening panel
    usage: /moditem

  disable:
    description: Disable command an all server of for admin
    usage: /disable <command> + <player>

  enable:
    description: Enable command an all server of for admin
    usage: /enable <command> + <player>









